### ISSUE TITLE
Road to 4.0

### ISSUE THREAD

**Issue by alcarney** [CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io#106]
- [x]  Finish implementing themes properly, the entire css for the site needs to be controlled from a single css file generated from sass. The following files still need to be incorporated into this system 
    - [x] flexnav.css (fixed in #114) 
    - [x] slicknav.css (fixed in #113)
    - [x] sessions.css (fixed in #113)

- [x] Add a "We need you!" poster to pages which are lacking content to try and encourage contributions to the site (done in #100)
