### ISSUE TITLE
Move all content to a collection

### ISSUE THREAD

**Issue by alcarney** [CardiffMathematicsCodeClub/CardiffMathematicsCodeClub.github.io#118]
In a bid to keep the site consistent I think it would be best if all content on the site used the collection system. Hopefully this will keep template code more straightforward and be easier for new contributors to figure out how the site works

Content to be moved:

- [x] Languages (fixed by #120)
- [x] Editors - should this be renamed to tools to include things like git? (fixed by #123)  
- [x] Projects (fixed by #121)

**Comment by timothyf1** [comment]
@alcarney I don't mind doing some of this

**Comment by alcarney** [comment]
Cool :+1:
Knock yourself out :)
